// server/repositories/index.ts
export * from "./school-core/class.repository"
export * from "./school-core/school.repository"
export * from "./school-core/stream.repository"
export * from "./people/user.repository"
export * from "./people/super-admin.repository"
export * from "./people/student.repository"
export * from "./academics/subject.repository"
export * from "./academics/department.repository"
export * from "./academics/attendance.repository"
export * from "./academics/exam.repository"
export * from "./academics/examResult.repository"
export * from "./finance/fee.repository"
export * from "./finance/feePayment.repository"
export * from "./finance/invoice.repository"
export * from "./finance/invoiceItem.repository"
export * from "./finance/payment.repository"
export * from "./security/login.repository"
export * from "./security/password-reset.repository"
export * from "./security/session.repository"
export * from "./permissions/permission.repository"
export * from "./permissions/role.repository"
export * from "./permissions/rolePermission.repository"
export * from "./allocation.repository"
export * from "./event.repository"
export * from "./notification.repository"



